[project]
name = "python-process"
version = "0.0.1"
description = "a python socket server implementation of a vivarium process"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["ipdb"]
